桂林新闻综合:
  name:
  - 桂林新闻综合
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvsou: 123b1ef3
    tvmao: GLXW
桂林公共频道:
  name:
  - 桂林公共频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvsou: 2ca58f72
    tvmao: GLGG
桂林科教旅游:
  name:
  - 桂林科教旅游
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvsou: e3ec53f2
    tvmao: GLKJLY
贵港新闻综合:
  name:
  - 贵港新闻综合
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvsou: 1117ed28
    tvmao: GGTV1
贵港公共:
  name:
  - 贵港公共
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvsou: d9bfc9f6
    tvmao: GGTV2
梧州新闻综合:
  name:
  - 梧州新闻综合
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvsou: c68ba5e9
    tvmao: GXWZTV1
梧州公共:
  name:
  - 梧州公共
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvsou: d9177e5d
    tvmao: GXWZTV2
梧州教育生活:
  name:
  - 梧州教育生活
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvsou: b08c7424
    tvmao: GXWZTV3
贺州综合:
  name:
  - 贺州综合
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvmao: GXHZTV1
魅力时尚:
  name:
  - 魅力时尚
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvmao: IPTVMLSS
热播剧场:
  name:
  - 热播剧场
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvmao: IPTVRBJC
IPTV法治:
  name:
  - IPTV法治
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvmao: IPTVFZ
少儿动画:
  name:
  - 少儿动画
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvmao: IPTVSEDH
收视指南:
  name:
  - 收视指南
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvmao: IPTVSEDH
IPTV野外:
  name:
  - IPTV野外
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvsou: c541a7db
    tvmao: IPTVYW
爱综艺:
  name:
  - 爱综艺
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvsou: 4c6e941d
爱体育:
  name:
  - 爱体育
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvsou: 36837a08
爱电影:
  name:
  - 爱电影
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvsou: 329bb018
经典电影:
  name:
  - 经典电影
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvsou: 329bb018
爱大剧:
  name:
  - 爱大剧
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvsou: 6ba05d48
IPTV谍战剧场:
  name:
  - IPTV谍战剧场
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvsou: 3c16f304
    tvmao: IPTVDZJC
IPTV相声小品:
  name:
  - IPTV相声小品
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvsou: 5a09b2ed
    tvmao: IPTVXSXP
IPTV足球:
  name:
  - IPTV足球
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvmao: IPTVZUQIU
