柳州新闻综合:
  name:
  - 柳州新闻综合
  preview: 2
  recap: 7
  refresh: once
  scraper:
    51livetv: "1241"


南宁新闻综合:
  name:
  - 南宁新闻综合
  preview: 2
  recap: 7
  refresh: once
  scraper:
    51livetv: "1312"

南宁影视娱乐:
  name:
  - 南宁影视娱乐
  preview: 2
  recap: 7
  refresh: once
  scraper:
    51livetv: "1313"

南宁文旅生活:
  name:
  - 南宁文旅生活
  preview: 2
  recap: 7
  refresh: once
  scraper:
    51livetv: "1314"

南宁公共:
  name:
  - 南宁公共
  preview: 2
  recap: 7
  refresh: once
  scraper:
    51livetv: "1315"

广西新闻:
  name:
  - 广西新闻
  preview: 2
  recap: 7
  refresh: once
  scraper:
    51livetv: "1112"

玉林新闻综合:
  name:
  - 玉林新闻综合
  preview: 2
  recap: 7
  refresh: once
  scraper:
    51livetv: "1759"

梧州新闻综合:
  name:
  - 梧州新闻综合
  preview: 2
  recap: 7
  refresh: once
  scraper:
    51livetv: "1926"

北海新闻综合:
  name:
  - 北海新闻综合
  preview: 2
  recap: 7
  refresh: once
  scraper:
    51livetv: "2451"

河池新闻综合:
  name:
  - 河池新闻综合
  preview: 2
  recap: 7
  refresh: once
  scraper:
    51livetv: "2454"

贵港新闻综合:
  name:
  - 贵港新闻综合
  preview: 2
  recap: 7
  refresh: once
  scraper:
    51livetv: "2456"

防城港新闻综合:
  name:
  - 防城港新闻综合
  preview: 2
  recap: 7
  refresh: once
  scraper:
    51livetv: "2458"

崇左综合:
  name:
  - 崇左综合
  preview: 2
  recap: 7
  refresh: once
  scraper:
    51livetv: "2460"

来宾综合:
  name:
  - 来宾综合
  preview: 2
  recap: 7
  refresh: once
  scraper:
    51livetv: "2842"

百色综合:
  name:
  - 百色综合
  preview: 2
  recap: 7
  refresh: once
  scraper:
    51livetv: "2522"

桂林新闻综合:
  name:
  - 桂林新闻综合
  preview: 2
  recap: 7
  refresh: once
  scraper:
    51livetv: "2805"

钦州综合:
  name:
  - 钦州综合
  preview: 2
  recap: 7
  refresh: once
  scraper:
    51livetv: "2840"
魅力时尚:
  name:
  - 魅力时尚
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvmao: IPTVMLSS
热播剧场:
  name:
  - 热播剧场
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvmao: IPTVRBJC
IPTV法治:
  name:
  - IPTV法治
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvmao: IPTVFZ
少儿动画:
  name:
  - 少儿动画
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvmao: IPTVSEDH
收视指南:
  name:
  - 收视指南
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvmao: IPTVSEDH
爱综艺:
  name:
  - 爱综艺
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvsou: 4c6e941d
爱体育:
  name:
  - 爱体育
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvsou: 36837a08
爱电影:
  name:
  - 爱电影
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvsou: 329bb018
经典电影:
  name:
  - 经典电影
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvsou: 329bb018
爱大剧:
  name:
  - 爱大剧
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvsou: 6ba05d48
IPTV野外:
  name:
  - IPTV野外
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvsou: c541a7db
    tvmao: IPTVYW
IPTV谍战剧场:
  name:
  - IPTV谍战剧场
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvsou: 3c16f304
    tvmao: IPTVDZJC
IPTV相声小品:
  name:
  - IPTV相声小品
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvsou: 5a09b2ed
    tvmao: IPTVXSXP
IPTV足球:
  name:
  - IPTV足球
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvmao: IPTVZUQIU


