广西卫视:
  name:
    - 广西卫视
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "50"

广西电视台国际频道:
  name:
    - 广西电视台国际频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "1770"

广西综艺旅游频道:
  name:
    - 广西综艺旅游频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "174"

广西都市频道:
  name:
    - 广西都市频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "175"

广西公共频道:
  name:
    - 广西公共频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "176"

广西影视频道:
  name:
    - 广西影视频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "177"

广西乐思购频道:
  name:
    - 广西乐思购频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "178"

广西电视台新闻频道:
  name:
    - 广西电视台新闻频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "963"

柳州新闻综合:
  name:
    - 柳州新闻综合
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "195"

柳州科教频道:
  name:
    - 柳州科教频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "196"

柳州公共频道:
  name:
    - 柳州公共频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "197"

南宁电视台新闻综合频道:
  name:
    - 南宁电视台新闻综合频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "283"

南宁电视台影视娱乐频道:
  name:
    - 南宁电视台影视娱乐频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "284"

南宁电视台都市生活频道:
  name:
    - 南宁电视台都市生活频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "285"

南宁电视台公共频道:
  name:
    - 南宁电视台公共频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "286"

玉林电视台新闻综合频道:
  name:
    - 玉林电视台新闻综合频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "817"

玉林电视台公共频道:
  name:
    - 玉林电视台公共频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "818"

玉林电视台知识频道:
  name:
    - 玉林电视台知识频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "819"

梧州电视台新闻综合频道:
  name:
    - 梧州电视台新闻综合频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "1024"

梧州电视台公共影视频道:
  name:
    - 梧州电视台公共影视频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "1025"

快乐垂钓:
  name:
    - 快乐垂钓
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "1504"

北海电视台新闻综合频道:
  name:
    - 北海电视台新闻综合频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "1699"

北海电视台经济科教频道:
  name:
    - 北海电视台经济科教频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "1700"

北海电视台公共频道:
  name:
    - 北海电视台公共频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "1701"

河池电视台新闻综合频道:
  name:
    - 河池电视台新闻综合频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "1702"

河池电视台科教生活频道:
  name:
    - 河池电视台科教生活频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "1703"

贵港电视台新闻综合频道:
  name:
    - 贵港电视台新闻综合频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "1704"

贵港电视台公共频道:
  name:
    - 贵港电视台公共频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "1705"

防城港电视台新闻综合频道:
  name:
    - 防城港电视台新闻综合频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "1706"

防城港电视台公共频道:
  name:
    - 防城港电视台公共频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "1707"

崇左电视台新闻综合频道:
  name:
    - 崇左电视台新闻综合频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "1708"

百色电视台综合频道:
  name:
    - 百色电视台综合频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "1772"

百色电视台公共频道:
  name:
    - 百色电视台公共频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "1773"

桂林电视台新闻综合频道:
  name:
    - 桂林电视台新闻综合频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "2135"

桂林电视台公共频道:
  name:
    - 桂林电视台公共频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "2136"

桂林电视台科教旅游频道:
  name:
    - 桂林电视台科教旅游频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "2137"

钦州电视台综合频道:
  name:
    - 钦州电视台综合频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "2171"

钦州电视台公共频道:
  name:
    - 钦州电视台公共频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "2172"

来宾市电视台综合频道:
  name:
    - 来宾市电视台综合频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "2173"

来宾市电视台影视频道:
  name:
    - 来宾市电视台影视频道
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: "2174"
