'1232':
  name:
  - 南宁公共频道
  preview: 2
  recap: 6
  refresh: once
  scraper:
    51livetv: '1315'
    sports8: '286'
'1310':
  name:
  - 爱体育
  preview: 2
  recap: 6
  refresh: once
  scraper:
    sports8: '2869'
'162':
  name:
  - 中国天气
  preview: 2
  recap: 6
  refresh: once
  scraper:
    51livetv: '2047'
    sports8: '1168'
'190':
  name:
  - 爱大剧
  preview: 2
  recap: 6
  refresh: once
  scraper:
    sports8: '2871'
'2050':
  name:
  - CCTV4K
  preview: 2
  recap: 6
  refresh: once
  scraper:
    cctv: cctv4k
    51livetv: '3350'
    tvmao: CCTV4K
'3':
  name:
  - 卡酷动画
  preview: 2
  recap: 6
  refresh: once
  scraper:
    51livetv: '1131'
    sports8: '69'
    tvmao: BTV10
'330':
  name:
  - IPTV足球
  preview: 2
  recap: 6
  refresh: once
  scraper:
    tvmao: NMGZQ
'58':
  name:
  - 少儿动画
  preview: 2
  recap: 6
  refresh: once
  scraper:
    sports8: '2878'
    tvmao: IPTVSEDH
'59':
  name:
  - 爱综艺
  preview: 2
  recap: 6
  refresh: once
  scraper:
    sports8: '2868'
'61':
  name:
  - 魅力时尚
  preview: 2
  recap: 6
  refresh: once
  scraper:
    sports8: '2879'
    tvmao: IPTVMLSS
'62':
  name:
  - 爱电影
  preview: 2
  recap: 6
  refresh: once
  scraper:
    sports8: '2870'
'63':
  name:
  - 热播剧场
  preview: 2
  recap: 6
  refresh: once
  scraper:
    sports8: '2877'
    tvmao: IPTVRBJC
'64':
  name:
  - 经典电影
  preview: 2
  recap: 6
  refresh: once
  scraper:
    sports8: '2876'
'65':
  name:
  - 收视指南
  preview: 2
  recap: 6
  refresh: once
  scraper:
    sports8: '2880'
'70':
  name:
  - IPTV谍战剧场
  preview: 2
  recap: 6
  refresh: once
  scraper:
    sports8: '2872'
    tvmao: IPTVDZJC
'71':
  name:
  - IPTV野外
  preview: 2
  recap: 6
  refresh: once
  scraper:
    sports8: '2874'
    tvmao: IPTVYW
'72':
  name:
  - IPTV法治
  preview: 2
  recap: 6
  refresh: once
  scraper:
    sports8: '2875'
    tvmao: IPTVFZ
'73':
  name:
  - IPTV相声小品
  preview: 2
  recap: 6
  refresh: once
  scraper:
    sports8: '2873'
    tvmao: IPTVXSXP
'751':
  name:
  - CHC影迷电影
  preview: 2
  recap: 6
  refresh: once
  scraper:
    sports8: '1179'
    tvmao: CHC3
'752':
  name:
  - CHC动作电影
  preview: 2
  recap: 6
  refresh: once
  scraper:
    sports8: '1180'
    tvmao: CHC1
'753':
  name:
  - CHC家庭影院
  preview: 2
  recap: 6
  refresh: once
  scraper:
    sports8: '411'
    tvmao: CHC2
'754':
  name:
  - 先锋乒羽
  preview: 2
  recap: 6
  refresh: once
  scraper:
    tvmao: XFBY
'755':
  name:
  - 新动漫
  preview: 2
  recap: 6
  refresh: once
  scraper:
    sports8: '1181'
    tvmao: DONGMAN
'910000003':
  name:
  - 广西国际
  preview: 2
  recap: 6
  refresh: once
  scraper:
    51livetv: '2520'
    sports8: '1770'
    tvmao: GXGJ
'910000046':
  name:
  - 柳州新闻综合
  preview: 2
  recap: 6
  refresh: once
  scraper:
    51livetv: '1241'
    sports8: '195'
    tvmao: GXLZTV1
'910000047':
  name:
  - 北海新闻综合
  preview: 2
  recap: 6
  refresh: once
  scraper:
    51livetv: '2451'
    sports8: '1699'
    tvmao: BHTV1
'910000048':
  name:
  - 桂林新闻综合
  preview: 2
  recap: 6
  refresh: once
  scraper:
    51livetv: '2805'
    sports8: '2135'
    tvmao: GLXW
'910000049':
  name:
  - 贺州综合
  preview: 2
  recap: 6
  refresh: once
  scraper:
    tvmao: GXHZTV1
'910000050':
  name:
  - 玉林新闻综合
  preview: 2
  recap: 6
  refresh: once
  scraper:
    51livetv: '1759'
    sports8: '817'
    tvmao: GXYLTV1
'910000051':
  name:
  - 百色综合
  preview: 2
  recap: 6
  refresh: once
  scraper:
    51livetv: '2522'
    sports8: '1772'
    tvmao: BSTV1
'910000053':
  name:
  - 防城港新闻综合
  preview: 2
  recap: 6
  refresh: once
  scraper:
    51livetv: '2458'
    sports8: '1706'
    tvmao: FCGTV1
'910000054':
  name:
  - 精彩影视
  preview: 2
  recap: 6
  refresh: once
  scraper:
    sports8: '2821'
    tvmao: HSJCYS
'910000055':
  name:
  - 求索纪录
  preview: 2
  recap: 6
  refresh: once
  scraper:
    sports8: '2793'
    tvmao: QSJL
'910000058':
  name:
  - 钦州综合
  preview: 2
  recap: 6
  refresh: once
  scraper:
    51livetv: '2840'
    sports8: '2171'
    tvmao: QZTVCA1
'910000060':
  name:
  - 河池新闻综合
  preview: 2
  recap: 6
  refresh: once
  scraper:
    51livetv: '2454'
    sports8: '1702'
    tvmao: HCHTV1
'910000062':
  name:
  - 来宾综合
  preview: 2
  recap: 6
  refresh: once
  scraper:
    51livetv: '2842'
    sports8: '2173'
    tvmao: LBTVCA1
'910000063':
  name:
  - 贵港新闻综合
  preview: 2
  recap: 6
  refresh: once
  scraper:
    51livetv: '2456'
    sports8: '1704'
    tvmao: GGTV1
'910000064':
  name:
  - 崇左综合
  preview: 2
  recap: 6
  refresh: once
  scraper:
    51livetv: '2460'
    sports8: '1708'
    tvmao: GXCZTV1
'910000070':
  name:
  - 梧州新闻综合
  preview: 2
  recap: 6
  refresh: once
  scraper:
    51livetv: '1926'
    sports8: '1024'
    tvmao: GXWZTV1
'910000072':
  name:
  - 中国交通
  preview: 2
  recap: 6
  refresh: once
  scraper:
    sports8: '1304'
    tvmao: ZGJTPD
'910000073':
  name:
  - 桂林科教旅游
  preview: 2
  recap: 6
  refresh: once
  scraper:
    sports8: '2137'
    tvmao: GLKJLY
'910000074':
  name:
  - 桂林公共频道
  preview: 2
  recap: 6
  refresh: once
  scraper:
    sports8: '2136'
    tvmao: GLGG
