'20000072':
  name:
  - 南方卫视
  preview: 2
  recap: 1
  refresh: once
  scraper:
    51livetv: '1164'
    sports8: '102'
'94':
  name:
  - 南方卫视
  preview: 2
  recap: 1
  refresh: once
  scraper:
    51livetv: '1164'
    sports8: '102'
'532153587':
  name:
  - 游戏风云
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: '913'
'532153736':
  name:
  - 欢笑剧场
  preview: 2
  recap: 1
  refresh: once
  scraper:
    sports8: '911'
'532153592':
  name:
  - 魅力足球
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvmao: YULE
'910000049':
  name:
  - 贺州综合
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvmao: GXHZTV1
'910000057':
  name:
  - 贺州综合
  preview: 2
  recap: 1
  refresh: once
  scraper:
    tvmao: GXHZTV1
'910000070':
  name:
  - 梧州新闻综合
  preview: 2
  recap: 1
  refresh: once
  scraper:
    51livetv: '1926'
    sports8: '1024'
    tvmao: GXWZTV1
'910000076':
  name:
  - 梧州新闻综合
  preview: 2
  recap: 1
  refresh: once
  scraper:
    51livetv: '1926'
    sports8: '1024'
    tvmao: GXWZTV1
