CHC家庭影院:
  name:
    - CHC家庭影院
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "411"
    
CHC动作电影:
  name:
    - CHC动作电影
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "1180"
    
CHC影迷电影:
  name:
    -  CHC影迷电影
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "1179"
    
广西卫视:
  name:
    - 广西卫视
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "1179"

广西卫视:
  name:
    - 广西卫视
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "50"

广西国际:
  name:
    - 广西国际
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "1770"

广西综艺旅游:
  name:
    - 广西综艺旅游
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "174"

广西都市:
  name:
    - 广西都市
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "175"

广西公共:
  name:
    - 广西公共
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "176"

广西影视:
  name:
    - 广西影视
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "177"

广西乐思购:
  name:
    - 广西乐思购
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "178"

广西新闻:
  name:
    - 广西新闻
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "963"

柳州新闻综合:
  name:
    - 柳州新闻综合
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "195"

柳州科教:
  name:
    - 柳州科教
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "196"

柳州公共:
  name:
    - 柳州公共
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "197"

南宁新闻综合:
  name:
    - 南宁新闻综合
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "283"

南宁影视娱乐:
  name:
    - 南宁影视娱乐
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "284"

南宁文旅生活:
  name:
    - 南宁文旅生活
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "285"

南宁公共:
  name:
    - 南宁公共
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "286"

玉林新闻综合:
  name:
    - 玉林新闻综合
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "817"

玉林公共:
  name:
    - 玉林公共
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "818"

玉林知识:
  name:
    - 玉林知识
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "819"

梧州新闻综合:
  name:
    - 梧州新闻综合
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "1024"

梧州公共影视:
  name:
    - 梧州公共影视
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "1025"

北海新闻综合:
  name:
    - 北海新闻综合
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "1699"

北海经济科教:
  name:
    - 北海经济科教
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "1700"

北海公共:
  name:
    - 北海公共
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "1701"

河池新闻综合:
  name:
    - 河池新闻综合
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "1702"

河池科教生活:
  name:
    - 河池科教生活
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "1703"

贵港新闻综合:
  name:
    - 贵港新闻综合
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "1704"

贵港公共:
  name:
    - 贵港公共
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "1705"

防城港新闻综合:
  name:
    - 防城港新闻综合
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "1706"

防城港公共:
  name:
    - 防城港公共
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "1707"

崇左新闻综合:
  name:
    - 崇左新闻综合
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "1708"

百色综合:
  name:
    - 百色综合
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "1772"

百色公共:
  name:
    - 百色公共
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "1773"

桂林新闻综合:
  name:
    - 桂林新闻综合
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "2135"

桂林公共频道:
  name:
    - 桂林公共频道
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "2136"

桂林科教旅游:
  name:
    - 桂林科教旅游
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "2137"

钦州综合:
  name:
    - 钦州综合
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "2171"

钦州公共:
  name:
    - 钦州公共
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "2172"

来宾综合:
  name:
    - 来宾综合
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "2173"

来宾影视:
  name:
    - 来宾影视
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "2174"


收视指南:
  name:
  - 收视指南
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "2880"

爱体育:
  name:
  - 爱体育
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "2869"


魅力时尚:
  name:
  - 魅力时尚
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "2879"

少儿动画:
  name:
  - 少儿动画
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "2878"

热播剧场:
  name:
  - 热播剧场
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "2877"

经典电影:
  name:
  - 经典电影
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "2876"

IPTV法治:
  name:
  - IPTV法治
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "2875"

IPTV野外:
  name:
  - IPTV野外
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "2874"

IPTV相声小品:
  name:
  - IPTV相声小品
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "2873"

IPTV谍战剧场:
  name:
  - IPTV谍战剧场
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "2872"

爱大剧:
  name:
  - 爱大剧
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "2871"

爱电影:
  name:
  - 爱电影
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "2870"

爱综艺:
  name:
  - 爱综艺
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "2868"

卡酷动画:
  name:
    - 卡酷动画
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "69"

求索纪录:
  name:
    - 求索纪录
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "2793"

精彩影视:
  name:
    - 精彩影视
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "2821"

中国天气:
  name:
    -   中国天气
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "1168"

中国交通:
  name:
    -   中国交通
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "1304"

新动漫:
  name:
    -   新动漫
  preview: 2
  recap: 7
  refresh: once
  scraper:
    sports8: "1181"
